# Generated by Django 5.0.1 on 2024-01-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompressLink_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectiontable',
            name='urlredirection',
            field=models.URLField(max_length=2083),
        ),
    ]
