# Generated by Django 5.0.1 on 2024-01-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompressLink_App', '0003_redirectiontable_nombreutilisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectiontable',
            name='nombreutilisation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
